### ISSUE TITLE
Difference in turn_count if you request the context is returned for conversation_start special condition.

### ISSUE THREAD

**Issue by davidmeredith** [watson-developer-cloud/java-sdk#1046] opened 2019-03-22 10:31 UTC
Hi there,
I've encountered a difference in behaviour when invoking a dialog that defines a 'conversation_start' special condition depending on whether you request the context is returned (or not). It appears that returning the context on the first request invocation produces a different turn_count value compared to when you don't request the context is returned. The test below demonstrates this. I'd expect the turn_count values to be the same regardless of whether the context is returned, why the difference? 

Note, my conversation_start node inits some context vars and defines a small response sub-tree.
Thanks in advance, 
david 

```java
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import com.ibm.watson.developer_cloud.assistant.v2.Assistant;
import com.ibm.watson.developer_cloud.assistant.v2.model.*;
import org.junit.Test;

public class AssistantContextStartConvTest {

    private final String username = "xxxxx";
    private final String password = "xxxxxx";
    private final String assistantId = "xxxxxx";
    private final String VERSION = "2019-02-28";

    @Test
    public void includeOptionsOnConvesationStartTest(){
        Long turnCount1 = this.executeNewDialogSession(true); 
        Long turnCount2 = this.executeNewDialogSession(false); 

        // I'd expect the turn count values to be the same regardless of whether we requested 
        // the context to be returned in the first message or not, why the difference?
        assertTrue(turnCount1.equals(1L));
        assertTrue(turnCount2.equals(2L));
        // force a fail because we expect these values to be equal
        assertEquals(turnCount1, turnCount2); // java.lang.AssertionError: expected:<1> but was:<2>
    }

    private Long executeNewDialogSession(boolean includeInputOptionsOnConversation_Start) {
        Assistant service = this.createAssistantService();
        String sessionId = this.createSession(service);

        MessageInputOptions inputOptions = new MessageInputOptions();
        inputOptions.setReturnContext(new Boolean(true));

        MessageContext context = new MessageContext();
        MessageInput input; 
        // first message - should the first message return the context or not?
        if(includeInputOptionsOnConversation_Start){
            input = new MessageInput.Builder().text("First message").options(inputOptions).build();
        } else {
            input = new MessageInput.Builder().text("First message").build();
        }
        MessageOptions messageOptions = new MessageOptions.Builder(this.assistantId, sessionId)
                .input(input)
                .context(context)
                .build();
        MessageResponse messageResponse = service.message(messageOptions).execute();

        // second message
        context = messageResponse.getContext();
        input = new MessageInput.Builder().text("yes")
                .options(inputOptions)  // Request context is returned for 2nd message
                .build();
        messageOptions = new MessageOptions.Builder(this.assistantId, sessionId)
                .input(input)
                .context(context) // using context from previous message
                .build();
        messageResponse = service.message(messageOptions).execute();

        return messageResponse.getContext().getGlobal().getSystem().getTurnCount(); 
    }

    private Assistant createAssistantService() {
        Assistant service = new Assistant(VERSION);
        service.setUsernameAndPassword(this.username, this.password);
        return service;
    }

    private String createSession(Assistant service) {
        CreateSessionOptions createSessionOptions = new CreateSessionOptions.Builder(this.assistantId).build();
        SessionResponse session = service.createSession(createSessionOptions).execute();
        return session.getSessionId();
    }
}
```

**Comment by germanattanasio** [comment] 2019-03-22 13:29
@davidmeredith did you try this with the `Try it out` feature in Assistant?

**Comment by davidmeredith** [comment] 2019-03-22 16:36
I don't see the issue using the `Try it out` tab in Assistant UI, but couldn't that be down to a number of reasons? E.g. does 'Try it out` tab in the Assistant UI use the java sdk under the hood?  if true, does it not request the context is returned when making the first request to the conversation_start node akin to my 2nd call of `executeNewDialogSession`?  Either way, is my assumption correct in that the turn_count values should be the same regardless of whether the context is returned?

**Comment by lpatino10** [comment] 2019-04-02 19:52
Hey @davidmeredith, thanks for the detailed description of the issue and the code sample. After taking a look it does seem strange to me as well.

I've reached out to the team who manages that actual API to try and confirm whether or not that's unexpected behavior before trying to debug anything. I'll keep you posted on the progress in this issue.

**Comment by davidmeredith** [comment] 2019-04-04 08:38
Great, thanks @lpatino10

**Comment by davidmeredith** [comment] 2019-10-18 07:28
hi, was this ever investigated and resolved?

**Comment by lpatino10** [comment] 2019-10-18 13:37
Hey sorry @davidmeredith, I never actually heard anything back from the API team and then this fell by the wayside. I'll try this again with the new release and see if the issue still pops up.

**Comment by mkistler** [comment] 2019-10-19 20:23
@mediumTaj This might be one to add to the outstanding service issues list.

**Comment by martin-labsky** [comment] 2019-12-04 09:39
The issue is with `.context(context) // using context from previous message` used for the 2nd turn.
The V2 message keeps context server-side and the client should just send context in when it needs to change some parts of it. This includes the `global.system.turn_count`. As when it is sent in by the client, the service assumes the client actually wants to reset the `turn_count` to the specified value and it does not increment the counter as it would do if the client did not send one.

Now the V1 message logic differs, as there all context has to be sent back and forth between the client and the service. So there the service always increments the turn counter whose previous value is assumed to be always sent in by the client.

**Comment by lpatino10** [comment] 2020-01-14 14:42
Closing since it looks to be resolved. Thanks @martin-labsky!

**Closed by lpatino10** 2020-01-14 14:42 UTC
Labels: support
