### ISSUE TITLE
New Alchemy API does not support standard characters

### ISSUE THREAD

**Issue by scprotz** [watson-developer-cloud/java-sdk#64] opened 2015-09-25 01:02 UTC
I get 
```
{"error":"unsupported-text-language", "code":400}
```
when running text that has characters like `&` in them.

I think we either need a definition of supported characters or some automated encoding in the method:
```
service.getEntities()
```

**Comment by scprotz** [comment] 2015-09-25 01:28
Some other characters that cause it to break: '-' and '/'.

**Comment by germanattanasio** [comment] 2015-09-25 13:40
I can reproduce the issue.. seems to be something related to how we encode the `form-urlencoded`.

**Comment by germanattanasio** [comment] 2015-10-16 21:20
I've added test cases and I think the problem is fixed.
Example:
```java
Map<String, Object> params = new HashMap<String, Object>();
String text = "Mr. Vice President, my old colleague from Massachusetts"+
"and your new Speaker & John McCormack, Members of the 87th Congress, "+
"ladies and gentlemen: -. *&^%$#@!@#$%^&*()";
params.put(AlchemyLanguage.TEXT, text);

Entities entities = service.getEntities(params);
Assert.assertNotNull(entities);
Assert.assertFalse(entities.getEntities().isEmpty());
```

**Comment by gcolmen** [comment] 2016-02-18 21:29
Hello, I know it's a closed issue, but I'm using this simple phrase (without any symbols):
"delete laboratory record"

And I'm getting the very same error. What could it be? Or how can I solve it?

Thanks in advance!

**Comment by tanmayb123** [comment] 2016-04-06 18:24
Hi! I'm also getting the same issue. This is when I use "Stephen Hillenburg". Is there a way I can specify that the input is in english? Thanks!

**Comment by gcolmen** [comment] 2016-04-07 00:05
Hi, I solved the problem by sending a parameter for the language when making the call:

params.put("language", "english");

(params is the Map containing the parameters for the call).

Hope it's useful.

gc

**Comment by tanmayb123** [comment] 2016-04-07 00:46
Thanks for the info, @gcolmen!
I was able to use this to create #226

**Comment by tanmayb123** [comment] 2016-04-09 01:31
I think we can close the issue now.

**Comment by germanattanasio** [comment] 2016-04-09 01:36
I'm going to wait until the next release which is on April 15.

**Closed** 2016-04-18 22:28 UTC
Labels: Alchemy

**Comment by shmarzooq** [comment] 2016-05-08 13:19
How we can set language as "English" when "alchemyObj.TextGetTaxonomy(str)" call to alchemy?
Please help.

**Comment by germanattanasio** [comment] 2016-05-09 02:56
```java
AlchemyLanguage service = new AlchemyLanguage();
service.setLanguage(LanguageSelection.ENGLISH)
service.taxonomy("type string here")
```

**Comment by shmarzooq** [comment] 2016-05-09 03:24
@germanattanasio: Thank you for this. I've already setup my code which is using `Document doc = alchemyObj.TextGetTaxonomy("my string")` where "alchemyObj" is of class "com.alchemyapi.api.AlchemyAPI"

Could you please tell where to set Language in this case ?

Thanks!!

**Comment by germanattanasio** [comment] 2016-05-09 03:31
@shmarzooq you are using a different SDK. Look at the README.md in this project and switch to use this SDK.

**Comment by shmarzooq** [comment] 2016-05-09 03:40
@germanattanasio Thank you for pointing it out. I will look into README.md and will see how the switching goes. I just don't want to redo the whole code again. I've almost finished my project using AlchemyAPI (calling AlchemyAPI, passing string, getting text-taxonomies, text-concepts, and parsing the returned XML). Just getting this language issue and rest it's working fine.
