### ISSUE TITLE
[tradeoff-analytics] Call to dilemmas() failing in Google stack

### ISSUE THREAD

**Issue by shekhargowda** [watson-developer-cloud/java-sdk#612] opened 2017-03-14 17:26 UTC
Error: 
```
[tradeoff-analytics] Call to dilemmas() failing in Google stack

Stack Trace:

Exception in thread "main" java.lang.RuntimeException: Unable to invoke no-args constructor for class com.ibm.watson.developer_cloud.tradeoff_analytics.v1.model.column.Column. 

Register an InstanceCreator with Gson for this type may fix this problem.
	at com.google.gson.internal.ConstructorConstructor$8.construct(ConstructorConstructor.java:167)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:162)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
	at com.google.gson.Gson.fromJson(Gson.java:795)
	at com.ibm.watson.developer_cloud.util.ResponseUtils.getObject(ResponseUtils.java:93)
	at com.ibm.watson.developer_cloud.util.ResponseConverterUtils$3.convert(ResponseConverterUtils.java:79)
	at com.ibm.watson.developer_cloud.util.ResponseConverterUtils$3.convert(ResponseConverterUtils.java:76)
	at com.ibm.watson.developer_cloud.service.WatsonService.processServiceCall(WatsonService.java:405)
	at com.ibm.watson.developer_cloud.service.WatsonService$1.execute(WatsonService.java:180)
	at com.buzzapps.myinsights.service.watson.TradeoffServiceImpl.run(TradeoffServiceImpl.java:149)
	at com.buzzapps.myinsights.service.watson.TradeoffServiceImpl.main(TradeoffServiceImpl.java:154)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.gson.internal.UnsafeAllocator$1.newInstance(UnsafeAllocator.java:48)
	at com.google.gson.internal.ConstructorConstructor$8.construct(ConstructorConstructor.java:164)
	... 16 more
Caused by: java.lang.InstantiationException: com.ibm.watson.developer_cloud.tradeoff_analytics.v1.model.column.Column
	at sun.misc.Unsafe.allocateInstance(Native Method)
```
- [x] JDK version  (1.8)
- [x] java-sdk version (3.6.0)

**Comment by germanattanasio** [comment] 2017-03-17 03:37
@shekhargowda do you have the code you are using ?

**Comment by shekhargowda** [comment] 2017-03-17 15:08
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Service;

import com.ibm.watson.developer_cloud.tradeoff_analytics.v1.TradeoffAnalytics;
import com.ibm.watson.developer_cloud.tradeoff_analytics.v1.model.Dilemma;
import com.ibm.watson.developer_cloud.tradeoff_analytics.v1.model.Option;
import com.ibm.watson.developer_cloud.tradeoff_analytics.v1.model.Problem;
import com.ibm.watson.developer_cloud.tradeoff_analytics.v1.model.column.CategoricalColumn;
import com.ibm.watson.developer_cloud.tradeoff_analytics.v1.model.column.Column;
import com.ibm.watson.developer_cloud.tradeoff_analytics.v1.model.column.Column.Goal;
import com.ibm.watson.developer_cloud.tradeoff_analytics.v1.model.column.DateColumn;
import com.ibm.watson.developer_cloud.tradeoff_analytics.v1.model.column.NumericColumn;

public class TradeoffServiceImpl implements TradeoffService {

	private static String password = "XXX";
	private static String username = "XXXXXX";

	public void run() {
		TradeoffAnalytics service = new TradeoffAnalytics();
		service.setUsernameAndPassword(username, password);

		Map<String, String> headers = new HashMap<String, String>();
		headers.put("X-Watson-Learning-Opt-Out", "true");
		service.setDefaultHeaders(headers);
		
		String price = "price";
		String weight = "weight";
		String brand = "brand";
		String rDate = "rDate";

		String apple = "Apple";
		String htc = "HTC";
		String samsung = "Samsung";
		String sony = "Sony";

		List<String> categories = new ArrayList<String>();
		categories.add(apple);
		categories.add(htc);
		categories.add(samsung);
		categories.add(sony);

		List<String> preferences = new ArrayList<String>();
		preferences.add(samsung);
		preferences.add(apple);
		preferences.add(htc);

		Problem problem = new Problem("phones");

		// Define the objectives.
		List<Column> columns = new ArrayList<Column>();
		problem.setColumns(columns);

		NumericColumn priceColumn = new NumericColumn();
		priceColumn.setKey(price);
		priceColumn.setGoal(Goal.MIN);
		priceColumn.setObjective(true);
		priceColumn.range(0, 400);
		priceColumn.setFullName("Price");
		priceColumn.setFormat("number:2");
		columns.add(priceColumn);

		NumericColumn weightColumn = new NumericColumn();
		weightColumn.setKey(weight);
		weightColumn.setGoal(Goal.MIN);
		weightColumn.setObjective(true);
		weightColumn.setFullName("Weight");
		weightColumn.setFormat("number:0");
		columns.add(weightColumn);

		CategoricalColumn brandColumn = new CategoricalColumn();
		brandColumn.setKey(brand);
		brandColumn.setGoal(Goal.MIN);
		brandColumn.setObjective(true);
		brandColumn.setRange(categories);
		brandColumn.setPreference(preferences);
		brandColumn.setFullName("Brand");
		columns.add(brandColumn);

		DateColumn rDateColumn = new DateColumn();
		rDateColumn.setKey(rDate);
		rDateColumn.setGoal(Goal.MIN);
		rDateColumn.setObjective(true);
		rDateColumn.setFullName("Release Date");
		rDateColumn.setFormat("date: 'MMM dd, yyyy'");
		columns.add(rDateColumn);

		// Define the options.
		List<Option> options = new ArrayList<Option>();
		problem.setOptions(options);

		HashMap<String, Object> galaxyS4Specs = new HashMap<String, Object>();
		galaxyS4Specs.put(price, 249);
		galaxyS4Specs.put(weight, 130);
		galaxyS4Specs.put(brand, samsung);
		galaxyS4Specs.put(rDate, "2013-04-29T00:00:00Z");
		options.add(new Option("1", "Galaxy S4").values(galaxyS4Specs));

		HashMap<String, Object> iphone5Specs = new HashMap<String, Object>();
		iphone5Specs.put(price, 349);
		iphone5Specs.put(weight, 112);
		iphone5Specs.put(brand, apple);
		iphone5Specs.put(rDate, "2012-09-21T00:00:00Z");
		options.add(new Option("2", "iPhone 5").values(iphone5Specs));

		HashMap<String, Object> oneSpecs = new HashMap<String, Object>();
		oneSpecs.put(price, 299);
		oneSpecs.put(weight, 112);
		oneSpecs.put(brand, htc);
		oneSpecs.put(rDate, "2013-03-01T00:00:00Z");
		options.add(new Option("3", "One").values(oneSpecs));

		HashMap<String, Object> galaxyS5Specs = new HashMap<String, Object>();
		galaxyS5Specs.put(price, 349);
		galaxyS5Specs.put(weight, 135);
		galaxyS5Specs.put(brand, samsung);
		galaxyS5Specs.put(rDate, "2014-04-29T00:00:00Z");
		options.add(new Option("4", "Galaxy S5").values(galaxyS5Specs));

		HashMap<String, Object> iphone6Specs = new HashMap<String, Object>();
		iphone6Specs.put(price, 399);
		iphone6Specs.put(weight, 118);
		iphone6Specs.put(brand, apple);
		iphone6Specs.put(rDate, "2013-09-21T00:00:00Z");
		options.add(new Option("5", "iPhone 6").values(iphone6Specs));

		HashMap<String, Object> iphone7Specs = new HashMap<String, Object>();
		iphone7Specs.put(price, 499);
		iphone7Specs.put(weight, 118);
		iphone7Specs.put(brand, apple);
		iphone7Specs.put(rDate, "2014-09-21T00:00:00Z");
		options.add(new Option("6", "iPhone 7").values(iphone7Specs));

		HashMap<String, Object> xperiaSpecs = new HashMap<String, Object>();
		xperiaSpecs.put(price, 199);
		xperiaSpecs.put(weight, 120);
		xperiaSpecs.put(brand, sony);
		xperiaSpecs.put(rDate, "2014-08-21T00:00:00Z");
		options.add(new Option("7", "Xperia").values(xperiaSpecs));

		// Call the service and get the problem resolution
		Dilemma dilemma = service.dilemmas(problem, true).execute();
		System.out.println(dilemma.toString());
	}

	public static void main(String args[]) {
		new TradeoffServiceImpl().run();
	}

}

**Comment by germanattanasio** [comment] 2017-03-31 02:59
I'm not able to reproduce your issue. I'm using 3.7.0.
```json
{
  "problem": {
    "columns": [
      {
        "key": "price",
        "type": "numeric",
        "goal": "min",
        "is_objective": true,
        "format": "number:2",
        "full_name": "Price",
        "range": {
          "low": 0.0,
          "high": 400.0
        }
      },
      {
        "key": "weight",
        "type": "numeric",
        "goal": "min",
        "is_objective": true,
        "format": "number:0",
        "full_name": "Weight"
      },
      {
        "key": "brand",
        "type": "categorical",
        "goal": "min",
        "is_objective": true,
        "full_name": "Brand",
        "range": [
          "Samsung",
          "Apple",
          "HTC"
        ]
      },
      {
        "key": "rDate",
        "type": "datetime",
        "goal": "min",
        "is_objective": true,
        "format": "date: 'MMM dd, yyyy'",
        "full_name": "Release Date"
      }
    ],
    "options": [
      {
        "key": "1",
        "name": "Galaxy S4",
        "values": {
          "price": 249.0,
          "weight": 130.0,
          "rDate": "2013-04-29T00:00:00Z",
          "brand": "Samsung"
        }
      },
      {
        "key": "2",
        "name": "iPhone 5",
        "values": {
          "price": 349.0,
          "weight": 112.0,
          "rDate": "2012-09-21T00:00:00Z",
          "brand": "Apple"
        }
      },
      {
        "key": "3",
        "name": "One",
        "values": {
          "price": 299.0,
          "weight": 112.0,
          "rDate": "2013-03-01T00:00:00Z",
          "brand": "HTC"
        }
      },
      {
        "key": "4",
        "name": "Galaxy S5",
        "values": {
          "price": 349.0,
          "weight": 135.0,
          "rDate": "2014-04-29T00:00:00Z",
          "brand": "Samsung"
        }
      },
      {
        "key": "5",
        "name": "iPhone 6",
        "values": {
          "price": 399.0,
          "weight": 118.0,
          "rDate": "2013-09-21T00:00:00Z",
          "brand": "Apple"
        }
      },
      {
        "key": "6",
        "name": "iPhone 7",
        "values": {
          "price": 499.0,
          "weight": 118.0,
          "rDate": "2014-09-21T00:00:00Z",
          "brand": "Apple"
        }
      },
      {
        "key": "7",
        "name": "Xperia",
        "values": {
          "price": 199.0,
          "weight": 120.0,
          "rDate": "2014-08-21T00:00:00Z",
          "brand": "Sony"
        }
      }
    ],
    "subject": "phones"
  },
  "resolution": {
    "map": {
      "anchors": [
        {
          "name": "price",
          "position": {
            "x": 0.0,
            "y": 0.0
          }
        },
        {
          "name": "weight",
          "position": {
            "x": 0.0,
            "y": 5.196152422706632
          }
        },
        {
          "name": "rDate",
          "position": {
            "x": 5.196152422706632,
            "y": 5.196152422706632
          }
        },
        {
          "name": "brand",
          "position": {
            "x": 5.196152422706632,
            "y": 0.0
          }
        }
      ],
      "config": {
        "drivers": {
          "r_fin": "1.0",
          "r_init": "0.6",
          "r_anchor_init": "0.6",
          "training_length": "100",
          "max_map_size": "200",
          "alpha_init": "0.75",
          "training_anchors": "1.0",
          "data_multiplier": "9"
        },
        "params": {
          "rInit": "2.0515563512592996",
          "rFinish": "1.0",
          "seed": "20000",
          "rAnchor": "1.0",
          "alpha_init": "0.75",
          "map_size": "27",
          "training_period": "100",
          "anchor_epoch": "3"
        }
      },
      "metrics": {
        "mqe": "NaN",
        "tau": "NaN",
        "somers": "NaN",
        "kappa": 1.0,
        "kappa_delta": "NaN",
        "weighted_kappa": "NaN",
        "final_kappa": 1.0
      },
      "nodes": [
        {
          "coordinates": {
            "x": 2.0,
            "y": 0.0
          },
          "solution_refs": [
            "1"
          ]
        },
        {
          "coordinates": {
            "x": 0.0,
            "y": 3.4641016151377544
          },
          "solution_refs": [
            "3"
          ]
        },
        {
          "coordinates": {
            "x": 3.0,
            "y": 3.4641016151377544
          },
          "solution_refs": [
            "2"
          ]
        }
      ],
      "version": "APIV1-ANN"
    },
    "solutions": [
      {
        "solution_ref": "1",
        "status": "FRONT"
      },
      {
        "solution_ref": "2",
        "status": "FRONT"
      },
      {
        "solution_ref": "3",
        "status": "FRONT"
      },
      {
        "solution_ref": "4",
        "status": "EXCLUDED",
        "excluded_by": [
          {
            "solution_ref": "1",
            "objectives": [
              {
                "key": "price",
                "difference": 100.0
              },
              {
                "key": "weight",
                "difference": 5.0
              },
              {
                "key": "rDate",
                "difference": 3.1536E10,
                "text": "365 days"
              }
            ]
          }
        ]
      },
      {
        "solution_ref": "5",
        "status": "EXCLUDED",
        "excluded_by": [
          {
            "solution_ref": "2",
            "objectives": [
              {
                "key": "price",
                "difference": 50.0
              },
              {
                "key": "weight",
                "difference": 6.0
              },
              {
                "key": "rDate",
                "difference": 3.1536E10,
                "text": "365 days"
              }
            ]
          }
        ]
      },
      {
        "solution_ref": "6",
        "status": "INCOMPLETE",
        "status_cause": {
          "error_code": "RANGE_MISMATCH",
          "message": "A column of a option is out of range. Option \"6\" has a value \"499\" in column: \"price\" that does not meet column range \"[0.0,400.0]\"",
          "tokens": [
            "price",
            "499",
            "[0.0,400.0]"
          ]
        }
      },
      {
        "solution_ref": "7",
        "status": "DOES_NOT_MEET_PREFERENCE",
        "status_cause": {
          "error_code": "DOES_NOT_MEET_PREFERENCE",
          "message": "Option \"7\" has a value \"Sony\" that does not meet preference for column: \"brand\" that does not meet column type \"CATEGORICAL\"",
          "tokens": [
            "brand"
          ]
        }
      }
    ]
  }
}
```

**Comment by germanattanasio** [comment] 2017-03-31 16:51
I'm closing this as it works with 3.7.0

**Closed by germanattanasio** 2017-03-31 16:51 UTC
Labels: bug, help wanted, question

**Comment by shekhargowda** [comment] 2017-04-07 19:01
@germanattanasio what version of jdk? I am still seeing this error.
Exception in thread "main" java.lang.RuntimeException: Unable to invoke no-args constructor for class com.ibm.watson.developer_cloud.tradeoff_analytics.v1.model.column.Column. Register an InstanceCreator with Gson for this type may fix this problem.
	at com.google.gson.internal.ConstructorConstructor$8.construct(ConstructorConstructor.java:167)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:162)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
	at com.google.gson.Gson.fromJson(Gson.java:795)
	at com.ibm.watson.developer_cloud.util.ResponseUtils.getObject(ResponseUtils.java:93)
	at com.ibm.watson.developer_cloud.util.ResponseConverterUtils$3.convert(ResponseConverterUtils.java:79)
	at com.ibm.watson.developer_cloud.util.ResponseConverterUtils$3.convert(ResponseConverterUtils.java:76)
	at com.ibm.watson.developer_cloud.service.WatsonService.processServiceCall(WatsonService.java:405)
	at com.ibm.watson.developer_cloud.service.WatsonService$1.execute(WatsonService.java:180)
	at com.buzzapps.myinsights.service.watson.TradeoffServiceImpl.run(TradeoffServiceImpl.java:149)
	at com.buzzapps.myinsights.service.watson.TradeoffServiceImpl.main(TradeoffServiceImpl.java:154)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.gson.internal.UnsafeAllocator$1.newInstance(UnsafeAllocator.java:48)
	at com.google.gson.internal.ConstructorConstructor$8.construct(ConstructorConstructor.java:164)
	... 16 more
Caused by: java.lang.InstantiationException: com.ibm.watson.developer_cloud.tradeoff_analytics.v1.model.column.Column
	at sun.misc.Unsafe.allocateInstance(Native Method)

**Comment by germanattanasio** [comment] 2017-04-07 19:48
3.7.1

**Comment by shekhargowda** [comment] 2017-04-07 20:15
@germanattanasio with 3.7.1
Message:
Apr 07, 2017 4:14:03 PM okhttp3.internal.platform.Platform log
INFO: --> POST https://gateway.watsonplatform.net/tradeoff-analytics/api/v1/dilemmas?generate_visualization=true http/1.1 (1364-byte body)
Apr 07, 2017 4:14:03 PM okhttp3.internal.platform.Platform log
INFO: <-- 200 OK https://gateway.watsonplatform.net/tradeoff-analytics/api/v1/dilemmas?generate_visualization=true (183ms, unknown-length body)
Exception in thread "main" java.lang.RuntimeException: Unable to invoke no-args constructor for class com.ibm.watson.developer_cloud.tradeoff_analytics.v1.model.column.Column. Register an InstanceCreator with Gson for this type may fix this problem.
	at com.google.gson.internal.ConstructorConstructor$8.construct(ConstructorConstructor.java:167)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:162)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
	at com.google.gson.Gson.fromJson(Gson.java:795)
	at com.ibm.watson.developer_cloud.util.ResponseUtils.getObject(ResponseUtils.java:93)
	at com.ibm.watson.developer_cloud.util.ResponseConverterUtils$3.convert(ResponseConverterUtils.java:79)
	at com.ibm.watson.developer_cloud.util.ResponseConverterUtils$3.convert(ResponseConverterUtils.java:76)
	at com.ibm.watson.developer_cloud.service.WatsonService.processServiceCall(WatsonService.java:416)
	at com.ibm.watson.developer_cloud.service.WatsonService$1.execute(WatsonService.java:191)
	at com.buzzapps.myinsights.service.watson.TradeoffServiceImpl.run(TradeoffServiceImpl.java:149)
	at com.buzzapps.myinsights.service.watson.TradeoffServiceImpl.main(TradeoffServiceImpl.java:154)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.gson.internal.UnsafeAllocator$1.newInstance(UnsafeAllocator.java:48)
	at com.google.gson.internal.ConstructorConstructor$8.construct(ConstructorConstructor.java:164)
	... 16 more
Caused by: java.lang.InstantiationException: com.ibm.watson.developer_cloud.tradeoff_analytics.v1.model.column.Column
	at sun.misc.Unsafe.allocateInstance(Native Method)

**Comment by shekhargowda** [comment] 2017-04-16 22:56
SDK Version: 3.7.1
               <dependency>
			<groupId>com.ibm.watson.developer_cloud</groupId>
			<artifactId>tradeoff-analytics</artifactId>
			<version>3.7.1</version>
		</dependency>

Code:
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Service;

import com.ibm.watson.developer_cloud.tradeoff_analytics.v1.TradeoffAnalytics;
import com.ibm.watson.developer_cloud.tradeoff_analytics.v1.model.Dilemma;
import com.ibm.watson.developer_cloud.tradeoff_analytics.v1.model.Option;
import com.ibm.watson.developer_cloud.tradeoff_analytics.v1.model.Problem;
import com.ibm.watson.developer_cloud.tradeoff_analytics.v1.model.column.CategoricalColumn;
import com.ibm.watson.developer_cloud.tradeoff_analytics.v1.model.column.Column;
import com.ibm.watson.developer_cloud.tradeoff_analytics.v1.model.column.Column.Goal;
import com.ibm.watson.developer_cloud.tradeoff_analytics.v1.model.column.DateColumn;
import com.ibm.watson.developer_cloud.tradeoff_analytics.v1.model.column.NumericColumn;


@Service
public class TradeoffServiceImpl implements TradeoffService {

	private static String password = "Q1CP8deUrcbM";
	private static String username = "c2448652-f16a-466f-88d9-d3d602f77a37";

	public void run() {
		TradeoffAnalytics service = new TradeoffAnalytics();
		service.setUsernameAndPassword(username, password);

		Map<String, String> headers = new HashMap<String, String>();
		headers.put("X-Watson-Learning-Opt-Out", "true");
		service.setDefaultHeaders(headers);
		
		String price = "price";
		String weight = "weight";
		String brand = "brand";
		String rDate = "rDate";

		String apple = "Apple";
		String htc = "HTC";
		String samsung = "Samsung";
		String sony = "Sony";

		List<String> categories = new ArrayList<String>();
		categories.add(apple);
		categories.add(htc);
		categories.add(samsung);
		categories.add(sony);

		List<String> preferences = new ArrayList<String>();
		preferences.add(samsung);
		preferences.add(apple);
		preferences.add(htc);

		Problem problem = new Problem("phones");

		// Define the objectives.
		List<Column> columns = new ArrayList<Column>();
		problem.setColumns(columns);

		NumericColumn priceColumn = new NumericColumn();
		priceColumn.setKey(price);
		priceColumn.setGoal(Goal.MIN);
		priceColumn.setObjective(true);
		priceColumn.range(0, 400);
		priceColumn.setFullName("Price");
		priceColumn.setFormat("number:2");
		columns.add(priceColumn);

		NumericColumn weightColumn = new NumericColumn();
		weightColumn.setKey(weight);
		weightColumn.setGoal(Goal.MIN);
		weightColumn.setObjective(true);
		weightColumn.setFullName("Weight");
		weightColumn.setFormat("number:0");
		columns.add(weightColumn);

		CategoricalColumn brandColumn = new CategoricalColumn();
		brandColumn.setKey(brand);
		brandColumn.setGoal(Goal.MIN);
		brandColumn.setObjective(true);
		brandColumn.setRange(categories);
		brandColumn.setPreference(preferences);
		brandColumn.setFullName("Brand");
		columns.add(brandColumn);

		DateColumn rDateColumn = new DateColumn();
		rDateColumn.setKey(rDate);
		rDateColumn.setGoal(Goal.MIN);
		rDateColumn.setObjective(true);
		rDateColumn.setFullName("Release Date");
		rDateColumn.setFormat("date: 'MMM dd, yyyy'");
		columns.add(rDateColumn);

		// Define the options.
		List<Option> options = new ArrayList<Option>();
		problem.setOptions(options);

		HashMap<String, Object> galaxyS4Specs = new HashMap<String, Object>();
		galaxyS4Specs.put(price, 249);
		galaxyS4Specs.put(weight, 130);
		galaxyS4Specs.put(brand, samsung);
		galaxyS4Specs.put(rDate, "2013-04-29T00:00:00Z");
		options.add(new Option("1", "Galaxy S4").values(galaxyS4Specs));

		HashMap<String, Object> iphone5Specs = new HashMap<String, Object>();
		iphone5Specs.put(price, 349);
		iphone5Specs.put(weight, 112);
		iphone5Specs.put(brand, apple);
		iphone5Specs.put(rDate, "2012-09-21T00:00:00Z");
		options.add(new Option("2", "iPhone 5").values(iphone5Specs));

		HashMap<String, Object> oneSpecs = new HashMap<String, Object>();
		oneSpecs.put(price, 299);
		oneSpecs.put(weight, 112);
		oneSpecs.put(brand, htc);
		oneSpecs.put(rDate, "2013-03-01T00:00:00Z");
		options.add(new Option("3", "One").values(oneSpecs));

		HashMap<String, Object> galaxyS5Specs = new HashMap<String, Object>();
		galaxyS5Specs.put(price, 349);
		galaxyS5Specs.put(weight, 135);
		galaxyS5Specs.put(brand, samsung);
		galaxyS5Specs.put(rDate, "2014-04-29T00:00:00Z");
		options.add(new Option("4", "Galaxy S5").values(galaxyS5Specs));

		HashMap<String, Object> iphone6Specs = new HashMap<String, Object>();
		iphone6Specs.put(price, 399);
		iphone6Specs.put(weight, 118);
		iphone6Specs.put(brand, apple);
		iphone6Specs.put(rDate, "2013-09-21T00:00:00Z");
		options.add(new Option("5", "iPhone 6").values(iphone6Specs));

		HashMap<String, Object> iphone7Specs = new HashMap<String, Object>();
		iphone7Specs.put(price, 499);
		iphone7Specs.put(weight, 118);
		iphone7Specs.put(brand, apple);
		iphone7Specs.put(rDate, "2014-09-21T00:00:00Z");
		options.add(new Option("6", "iPhone 7").values(iphone7Specs));

		HashMap<String, Object> xperiaSpecs = new HashMap<String, Object>();
		xperiaSpecs.put(price, 199);
		xperiaSpecs.put(weight, 120);
		xperiaSpecs.put(brand, sony);
		xperiaSpecs.put(rDate, "2014-08-21T00:00:00Z");
		options.add(new Option("7", "Xperia").values(xperiaSpecs));

		// Call the service and get the problem resolution
		Dilemma dilemma = service.dilemmas(problem, true).execute();
		System.out.println(dilemma.toString());
	}

	public static void main(String args[]) {
		new TradeoffServiceImpl().run();
	}

}
