### ISSUE TITLE
[speech-to-text] No results from recognizeUsingWebSockets() method

### ISSUE THREAD

**Issue by jeffpk62** [watson-developer-cloud/java-sdk#310] opened 2016-06-02 13:58 UTC
The following Java program (renamed for attachment) uses recognizeUsingWebSockets() to transcribe a simple WAV file: [STTrecognizeWS.txt](https://github.com/watson-developer-cloud/java-sdk/files/295751/STTrecognizeWS.txt).  German had informed me that WS support prior to the v3.0 SDK had some issues, and this may be an artifact of those.  But this program doesn't return any results, and it looks like it should (it's pretty much out of the example code).

Testing with **java-sdk-2.10.0-jar-with-dependencies.jar**.

**Comment by germanattanasio** [comment] 2016-06-06 19:22
@jeffpk62 The problem is probably related to the dependency we were using prior to `v3.0.0`. We were having some issues sending the WebSockets frames and that's why we switched to `okhttp-ws`.

I'm marking this as `wontfix` but this issue will help new issues facing the same problem.
The solution is to update the dependency to be >= `v3.0.0-RC1`

**Closed by germanattanasio** 2016-06-06 19:22 UTC
Labels: bug, speech-to-text, wontfix

**Comment by jeffpk62** [comment] 2016-06-06 19:30
I figured that would be the solution, German; that's cool.  I wanted to log it for future reference.  I think the test code is good, and I'll try again (with the required modifications for the async changes) when I have the cycles to migrate to v3.
