### ISSUE TITLE
Watson Alchemy date extraction not working in some scenarios in Java SDK

### ISSUE THREAD

**Issue by GarrettHamers** [watson-developer-cloud/java-sdk#609] opened 2017-03-09 13:40 UTC
The Alchemy date extraction is not working properly for the Java SDK. The date extraction is failing to find any dates with both the DateExtraction and CombinedCall API calls. The following are example strings that do not return any dates:

Show all results in 2016.
2016

I have narrowed down the problem to the jars contained in

```xml
<dependency>
    <groupId>com.ibm.watson.developer_cloud</groupId>
    <artifactId>java-sdk</artifactId>
</dependency>
```

I know this because I ran the same queries using the curl posts and the dates were extracted properly. In my environment, I use a custom model. I have confirmed that the custom model is not the issue though, as I have removed that factor, and the date extraction still fails.

Found some additional bugs with the date extraction. I am using the following as an anchorDate: Mon Feb 27 10:36:59 CST 2017.

1) What happened to shipment SHxMPOIPxAxGx170224x1 from last week.
This is the date extracted out by Watson Alchemy.
```json
"dates": [
{
"date": "2017-03-06T10:36:59.000",
"text": "from last week"
}
]
```
I expect the date to be 2017-02-20.

2) Show purchase orders from February.
This is the date extracted out by Watson Alchemy.
```json
"dates": [
{
"date": "2017-03-01T00:00:00.000",
"text": "from february"
}
]
```
I expect the date to be inclusive with the month that is specified in the text. So in this case, I expect a value of 2017-02-01.

Here is a list of some date extraction queries that are working correctly:
Show purchase order TPA0002 in 2016
show shipment number 169676326 and from 10/15/2016 to 09-21-2015
Display invoice 012615466 that happened last Saturday

**Comment by germanattanasio** [comment] 2017-03-13 20:23
Hey @GarrettHamers we are looking into it. No ETA yet.

**Comment by germanattanasio** [comment] 2017-03-31 02:54
@GarrettHamers
After some experiments I realized that:
```
from last week => next week
from February => first day of current month.
```
This is not a bug in the SDK, it's coming from the service so I will communicate this to them.
Did you try using Natural Language Understanding?
https://natural-language-understanding-demo.mybluemix.net/

**Comment by GarrettHamers** [comment] 2017-03-31 11:34
@germanattanasio  Please reopen this issue.  You did not solve the problem with extracting out the year from some queries.  

Show all results in 2016.
2016

I have tested this scenario in the Java SDK and in curl posts.  These queries do not work in the Java SDK, but they do work in the curls.

**Comment by GarrettHamers** [comment] 2017-03-31 11:41
@germanattanasio I do not have the option to switch over to the Natural Language Understanding as my team as paid for Watson Alchemy, and has not paid for Natural Language Understanding.  Therefore, we need to have the situation solved for Watson Alchemy.  If you have figured out this isn't a problem in the SDK, then I need this bug to be escalated to the correct team.  So which team should be responsible for the secondary problem described in this issue?  Where exactly am I supposed to make this issue?

**Comment by germanattanasio** [comment] 2017-03-31 13:34
I'm letting the development team know and they are looking at the issue

**Comment by germanattanasio** [comment] 2017-04-03 17:02
@blakesteve I think this could be an error in the way we parse the dates in the SDK. Can you please take a look?

**Comment by blakesteve** [comment] 2017-04-03 18:04
Sure thing, looking into it now

**Comment by blakesteve** [comment] 2017-04-13 22:30
@GarrettHamers can you provide some curl posts which worked for you but did not work via the java SDK? 
I've found that the java SDK is returning matching results as the curl attempts I've tried. 

For instance:
`curl -X POST -d "outputMode=json" -d "text=shipment from last week" -d "anchorDate=2017-04-13 16:32:31" "https://gateway-a.watsonplatform.net/calls/text/TextExtractDates?apikey=
$API_KEY`
incorrectly returns the date a week in advance:
```json
"dates": [
        {
            "date": "20170420T163231",
            "text": "from last week"
        }
    ]
```
however:
`curl -X POST -d "outputMode=json" -d "text=last week" -d "anchorDate=2017-04-13 16:32:31" "https://gateway-a.watsonplatform.net/calls/text/TextExtractDates?apikey=
$API_KEY`
correctly returns the the start date of the previous week:
```json
"dates": [
        {
            "date": "20170402T000000",
            "text": "last week"
        }
    ]```

and these results are consistent via curl or through the Java SDK, which leads me to agree with @germanattanasio 's initial assessment that the issue resides in the service itself.

**Comment by GarrettHamers** [comment] 2017-04-14 11:38
These are the queries that give correct results in the direct rest call, but not in the Java SDK.
**Show all results in 2016.
2016**

**Comment by blakesteve** [comment] 2017-04-17 18:41
Hi @GarrettHamers 

I'm seeing consistent (incorrect) results for both queries between a direct curl and the java sdk. Both **Show all results in 2016.** and
**2016**
return an empty array for dates:
```json
{
    "status": "OK",
    "usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
    "totalTransactions": "1",
    "language": "english",
    "dates": []
}
```
Can you try a curl post for both queries again? 
At this point I believe this is something that can only be fixed within the service itself.

**Comment by GarrettHamers** [comment] 2017-04-17 19:07
There is a problem in both layers.  After doing some testing, the dates are being extracted out when there isn't a model id or anchor date included.  When an anchor date or model id are included the dates are not being extracted.

![rest](https://cloud.githubusercontent.com/assets/26303327/25100768/6bbb7384-237f-11e7-8921-93663908e94c.PNG)

`<results>
<status>OK</status>
<usage>By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html</usage>
<totalTransactions>1</totalTransactions>
<language>english</language>
<dates>
<element>
<date>20160101T000000</date>
<text>2016</text>
 </element>
</dates>
 </results>`

**Comment by blakesteve** [comment] 2017-04-17 22:43
I just tested without anchor date, and **Show all results in 2016.** does return 
```json
{
  "date": "2016-01-01T00:00:00.000",
  "text": "2016"
}
```

However, I am failing to see any discrepancy between the results through the SDK vs a direct curl post.

Curl post with anchorDate included:
`curl -X POST -d "outputMode=json" -d "text=Show all results in 2016." -d "anchorDate=2016-04-13 16:32:31" "https://gateway-a.watsonplatform.net/calls/text/TextExtractDates?apikey=API_KEY"`

returns:
```json
{
    "status": "OK",
    "usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
    "totalTransactions": "1",
    "language": "english",
    "dates": []
}
```
Setting the test in the SDK with the same query and an anchorDate:
```java
public void testGetDates() {
    final Map<String, Object> params = new HashMap<String, Object>();
    params.put(AlchemyLanguage.TEXT, "Show all results in 2016.");
    try {
      params.put(AlchemyLanguage.ANCHOR_DATE, new Date());

    } catch (Exception e) {
      e.printStackTrace();
    }

    final Dates dates = service.getDates(params).execute();
    Assert.assertNotNull(dates);
    Assert.assertNotNull(dates.getDates());
    Assert.assertFalse(dates.getDates().isEmpty());
  }
```

also returns:
```json
{
  "dates": [],
  "language": "english",
  "totalTransactions": 1
}
```
Curl with same query but anchorDate omitted:
`url -X POST -d "outputMode=json" -d "text=Show all results in 2016." "https://gateway-a.watsonplatform.net/calls/text/TextExtractDates?apikey=API_KEY"`

returns:
```json
{
    "status": "OK",
    "usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
    "totalTransactions": "1",
    "language": "english",
    "dates": [
        {
            "date": "20160101T000000",
            "text": "2016"
        }
    ]
}
```
same query in java SDK, anchorDate removed:
```java
  public void testGetDates() {
    final Map<String, Object> params = new HashMap<String, Object>();
    params.put(AlchemyLanguage.TEXT, "Show all results in 2016.");

    final Dates dates = service.getDates(params).execute();
    Assert.assertNotNull(dates);
    Assert.assertNotNull(dates.getDates());
    Assert.assertFalse(dates.getDates().isEmpty());
  }
```
returns:
```json
{
  "dates": [
    {
      "date": "2016-01-01T00:00:00.000",
      "text": "2016"
    }
  ],
  "language": "english",
  "totalTransactions": 1
}
```

After multiple tests, I have consistently received incorrect results with queries you specified.
`Show all results in 2016.`
and
`2016`
return an empty array in `dates` if there is an anchorDate present. If not, they return correctly.
`shipment from last week`
incorrectly returns the date a week in advance. however,
`last week`
correctly returns the the start date of the previous week.

All of these results, the correct *and* the incorrect results, are consistent between the attempts through the java SDK and the equivalent curl post. After thorough testing, I have not been able to reproduce a call to the Watson service that returns a different value in the java SDK than what is returned with a curl post.

my local environment:
```
java -version
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)
```
and the Java SDK version 3.7.2

At this point I will work with @germanattanasio to communicate to the service team the issue, as I have confirmed that there is bug with the service itself.

**Comment by GarrettHamers** [comment] 2017-04-18 11:33
@germanattanasio @blakesteve How is the issue going to be transferred to the "service team"?  I need to have a way to track the progress of the problems presented in this issue.

**Comment by germanattanasio** [comment] 2017-04-19 21:18
Hi @GarrettHamers,

I talked to the development team and now that we know that this is not an issue in the SDK they will investigate on their side. No ETA on when they would be able to look at the issue. You should be able to open a support ticket here: https://support.ibmcloud.com/Support/5377/5383/en-us/Portal/Index


I'm closing this issue because it's not a problem in the SDK.

**Closed by germanattanasio** 2017-04-19 21:18 UTC
Labels: Alchemy, bug
