### ISSUE TITLE
Tradeoff Analytics Example Out-Of-Sync

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/java-sdk#83] opened 2015-10-15 20:02 UTC
The Tradeoff Analytics example contained within the repository's readme does not seem to be consistent with the most recent version of the API you provide for the Tradeoff Analytics service.

While investigating the use of your Java SDK in an application we are building at the Mobile Innovation Lab, I started by trying to execute the provided example in the readme. Unfortunately, it failed to compile.

The source code of the Tradeoff Analytics test, however, compiles. Perhaps the API you provide for Tradeoff Analytics was updated, but the readme was not updated to reflect those changes?

**Comment by germanattanasio** [comment] 2015-10-16 01:28
duplicate of #82

**Comment by germanattanasio** [comment] 2015-10-16 01:29
I will be updating the example and code for Tradeoff Analytics in #82

**Closed by germanattanasio** 2015-10-16 01:28 UTC
