### ISSUE TITLE
Checkstyle causes gradle build to fail

### ISSUE THREAD

**Issue by kognate** [watson-developer-cloud/java-sdk#712] opened 2017-05-31 15:54 UTC
There are checkstyle errors causing the gradle build
to fail.  These are mostly (very) minor issues.

**Comment by mkistler** [comment] 2017-05-31 20:04
@kognate I am unable to reproduce the checkstyle errors in my environment.  Any thoughts on why?

**Comment by germanattanasio** [comment] 2017-06-03 03:01
@mkistler I found that it depends on the JDK you are using.

**Comment by germanattanasio** [comment] 2017-06-16 02:00
fixed in the previous pull request

**Closed by germanattanasio** 2017-06-16 02:00 UTC
