### ISSUE TITLE
Dynamic variables set to null are not returned from/sent to API

### ISSUE THREAD

**Issue by lpatino10** [watson-developer-cloud/java-sdk#959] opened 2018-06-29 21:06 UTC
Currently, there's an issue where dynamic variables set to `null` are not serialized/deserialized properly when interacting with the API. An example of this is that the following `Workspace` object:

```json
{
  "name" : "Pizza app",
  "language" : "en",
  "metadata" : { },
  "description" : "Pizza app",
  "status" : "Available",
  "workspace_id" : "pizza_app-e0f3",
  "learning_opt_out" : false,
  "dialog_nodes": [
    {
      "dialog_node": "dialogNode",
      "context": {
        "dynamic_var": null
      }
    }
  ]
}
```

would not have its `dynamic_var` successfully passed to the Assistant service. Similarly, we wouldn't get this property in our Java object if it was set this way in the UI.

**Comment by jsstylos** [comment] 2018-07-02 14:37
Yes, we should probably prevent this in the Assistant v2 API (setting to null should be equivalent to removal).

**Comment by germanattanasio** [comment] 2018-07-03 02:00
I agree with Mike and Jeff.

I'm closing this since it's working as designed

**Comment by mkistler** [comment] 2018-07-05 16:30
Null is not an object.  If the behavior you want is to reset the context to be empty, the service should send an empty object.
```
"context": {}
```

**Comment by jsstylos** [comment] 2018-07-05 17:17
Is the issue with `context` itself being null or variables inside `context` being null? `context` itself should never be null.

**Comment by mkistler** [comment] 2018-07-09 17:44
Just had a chat with AndyS and I understand the issue better now.  There are legitimate use cases for explicitly encoding `null` _within_ application objects (e.g. to support JSON merging).  We need to think about how use can support these use cases with the SDKs.

**Comment by arajwade** [comment] 2018-07-12 07:00
Can you please provide an ETA for fixing this defect?
This has been filed by Support based on a use case from a BMC developer.

Thx.
--- Abhijit Rajwade
BMC Software

**Comment by lpatino10** [comment] 2018-07-13 19:52
I can't provide an ETA quite yet @arajwade but I'll get back to you when we have something concrete in mind.

**Comment by mkistler** [comment] 2018-10-09 14:41
It had fallen off the radar -- thanks for bringing it back up.  This is something we need to solve in a consistent way across all the SDKs.  I'll open an issue in our planning repo for this.

**Comment by jsstylos** [comment] 2018-10-16 15:30
Okay, digging more the issue is that null values are used to unset variables, and so you might legitimately want a dialog node that clears a value. Is there a link to an issue on (de)serialization of null value objects? Is there some other sentinel value we can use and wrap the base serializer?

**Comment by lpatino10** [comment] 2019-03-11 12:58
Taking a look at this for the upcoming major release. It does look like using `serializeNulls()` will at least handle those cases in this SDK so I think I'm going to make that change unless there are strong thoughts otherwise.

**Closed** 2019-03-28 21:20 UTC
Labels: invalid
