### ISSUE TITLE
[visual-recognition] Inputstream option in detectFaces does not detect images

### ISSUE THREAD

**Issue by MJonker** [watson-developer-cloud/java-sdk#1010] opened 2018-11-21 15:51 UTC
- [ to reproduce use this code]
```java
		File imageFile = new File("path to 2018-small.jpg");
		
		IamOptions options = new IamOptions.Builder()
				  .apiKey("<APIKEY>")
				  .build();

		VisualRecognition service = new VisualRecognition("2018-03-19", options);

		DetectFacesOptions detectFacesOptions = new DetectFacesOptions.Builder()
			  .imagesFile(imageFile)
			  .build();
		DetectedFaces result = service.detectFaces(detectFacesOptions).execute();
		System.out.println(result); //this works
				
//now read the file as bytes
		byte[] imageAsBytes =  Files.readAllBytes(Paths.get(imageFile.toURI()));
		ByteArrayInputStream bis = new ByteArrayInputStream(imageAsBytes);
		detectFacesOptions = new DetectFacesOptions.Builder()
				    	   		.imagesFile(bis)
				    			.build();
		result = service.detectFaces(detectFacesOptions).execute();// this does not work
		System.out.println(result); 
```
				

- [  Expected behavior ]
```
{
  "images_processed": 1,
  "images": [
    {
      "faces": [
        {
          "age": {
            "min": 45,
            "max": 48,
            "score": 0.9394793
          },
          "gender": {
            "gender": "MALE",
            "score": 0.9999987
          },
          "face_location": {
            "width": 150.0,
            "height": 201.0,
            "left": 187.0,
            "top": 101.0
          }
        }
      ],
      "image": "2018-small.jpg"
    }
  ]
}

```
- [  Actual behavior]
```java
   "error": {
        "code": 400,
        "description": "No images were specified.",
        "error_id": "input_error"
    },
    "images_processed": 0
```
- [ JDK version 8] 
- [ java-sdk version 6.9.3 (and 6.51)]

**Comment by lpatino10** [comment] 2019-03-11 13:10
Sorry @MJonker...this _really_ fell through the cracks.

The issue is actually still present in the latest version of the SDK. The workaround is that if you're supplying an `InputStream`, you need to set the `imagesFilename` on the builder as well, but that's pretty counterintuitive since you don't have to for the `File`.

It's on my list for upcoming `v7.0.0` changes/fixes. Sorry again for missing this.

**Comment by lpatino10** [comment] 2019-03-18 17:11
Just looked at this more closely and it actually _is_ expected behavior.

When users pass in a `File`, we set the filename automatically as a convenience because we can pull the name from that `File` object. This isn't something we can do with an `InputStream`.

I do still think we could do something small to mitigate this confusion, but it's not something high on the priority list right now. I've made an internal note to keep it in mind, but I'm going to close this issue since it's not a bug.

**Closed by lpatino10** 2019-03-18 17:11 UTC
Labels: bug, visual-recognition
