### ISSUE TITLE
okhttp errors in 3.0.0-RC1

### ISSUE THREAD

**Issue by g-may** [watson-developer-cloud/java-sdk#311] opened 2016-06-02 14:20 UTC
I ran into the following error on AlchemyLanguage/Concept Insights using a local clone of 3.0.0-RC1:

``` java
Exception in thread "main" java.lang.IllegalStateException: Unable to extract the trust manager on okhttp3.internal.Platform@af543f12, sslSocketFactory is class com.ibm.jsse2.SSLSocketFactoryImpl
	at okhttp3.OkHttpClient.<init>(OkHttpClient.java:187)
	at okhttp3.OkHttpClient.<init>(OkHttpClient.java:60)
	at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:718)
	at com.ibm.watson.developer_cloud.service.WatsonService.configureHttpClient(WatsonService.java:124)
	at com.ibm.watson.developer_cloud.service.WatsonService.<init>(WatsonService.java:103)
	at com.ibm.watson.developer_cloud.service.AlchemyService.<init>(AlchemyService.java:55)
	at com.ibm.watson.developer_cloud.alchemy.v1.AlchemyLanguage.<init>(AlchemyLanguage.java:54)
	at concept_insights_java.AlchemyRun.main(AlchemyRun.java:12)
```

I found this post https://github.com/square/okhttp/issues/2323#issuecomment-219833184 and tried upgrading the okhttp dependency from `3.2.0` to `3.3.1` in `pom.xml` of my clone, and was able to get things working.

**Comment by max-vogler** [comment] 2016-06-03 12:23
This is a duplicate of #264. It looks like you're the first to find a solution for it - good job :+1:

**Closed by max-vogler** 2016-06-03 12:23 UTC
Labels: duplicate
