### ISSUE TITLE
[retrieve-and-rank] RetrieveAndRank.rank(...) method returns 10 answers despite the topAnswers value

### ISSUE THREAD

**Issue by dkazakevich** [watson-developer-cloud/java-sdk#456] opened 2016-10-11 20:08 UTC
I use the following call (answersFile contains 1000 items):
```java
RetrieveAndRank.rank(ranker_id, answersFile, topAnswers).execute();
```
It's response always contains 10 answers despite the topAnswers value.
I tried R&R service Rest API and this functionality works fine.
I'm not sure, but you use the `"form-data; name=\"answer_metadata\""`, but the Rest API accept the  "answers" form-data.

**Comment by germanattanasio** [comment] 2016-10-14 21:41
Hi @gjs29 I'm assigning this to you. I can't reproduce it because I don't have a ranker. Can you please take a look?

**Comment by ajmorello** [comment] 2016-10-18 18:09
Related to Node fix https://github.com/watson-developer-cloud/java-sdk/issues/456

**Closed** 2016-10-18 19:52 UTC
Labels: bug, retrieve-and-rank
