### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/naming/InitialContext;

### ISSUE THREAD

**Issue by josephlam1984** [watson-developer-cloud/java-sdk#167] opened 2016-01-25 21:37 UTC
I recently upgraded to the latest version of 'com.ibm.watson.developer_cloud:java-sdk:2.7.0' in my Android application.  Upon building the project, I received the following error messages in logcat:

java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/naming/InitialContext;
                                                                     at com.ibm.watson.developer_cloud.util.CredentialUtils.getKeyUsingJNDI(CredentialUtils.java:125)
                                                                     at com.ibm.watson.developer_cloud.util.CredentialUtils.getAPIKey(CredentialUtils.java:93)
                                                                     at com.ibm.watson.developer_cloud.util.CredentialUtils.getAPIKey(CredentialUtils.java:76)
                                                                     at com.ibm.watson.developer_cloud.service.WatsonService.<init>(WatsonService.java:68)
                                                                     at com.ibm.watson.developer_cloud.visual_recognition.v2.VisualRecognition.<init>(VisualRecognition.java:74)

This line in CredentiallUtils.java is highlighted in red:
      Context context = new InitialContext();

**Comment by rohanag12** [comment] 2016-02-01 12:30
I received a similar message, here's my logcat:

W/art: Unresolved exception class when finding catch block: javax.naming.NamingException
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: cluck.fuster.watsonstt, PID: 20130
                                                                        java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/naming/InitialContext;
                                                                            at com.ibm.watson.developer_cloud.util.CredentialUtils.getKeyUsingJNDI(CredentialUtils.java:125)
                                                                            at com.ibm.watson.developer_cloud.util.CredentialUtils.getAPIKey(CredentialUtils.java:93)
                                                                            at com.ibm.watson.developer_cloud.util.CredentialUtils.getAPIKey(CredentialUtils.java:76)
                                                                            at com.ibm.watson.developer_cloud.service.WatsonService.<init>(WatsonService.java:68)
                                                                            at com.ibm.watson.developer_cloud.speech_to_text.v1.SpeechToText.<init>(SpeechToText.java:74)
                                                                            at cluck.fuster.watsonstt.MainActivity$3.onClick(MainActivity.java:88)
                                                                            at android.view.View.performClick(View.java:4794)
                                                                            at android.view.View$PerformClick.run(View.java:19905)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:139)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5308)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
                                                                         Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.naming.InitialContext" on path: DexPathList[[zip file "/data/app/cluck.fuster.watsonstt-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                            at com.ibm.watson.developer_cloud.util.CredentialUtils.getKeyUsingJNDI(CredentialUtils.java:125) 
                                                                            at com.ibm.watson.developer_cloud.util.CredentialUtils.getAPIKey(CredentialUtils.java:93) 
                                                                            at com.ibm.watson.developer_cloud.util.CredentialUtils.getAPIKey(CredentialUtils.java:76) 
                                                                            at com.ibm.watson.developer_cloud.service.WatsonService.<init>(WatsonService.java:68) 
                                                                            at com.ibm.watson.developer_cloud.speech_to_text.v1.SpeechToText.<init>(SpeechToText.java:74) 
                                                                            at cluck.fuster.watsonstt.MainActivity$3.onClick(MainActivity.java:88) 
                                                                            at android.view.View.performClick(View.java:4794) 
                                                                            at android.view.View$PerformClick.run(View.java:19905) 
                                                                            at android.os.Handler.handleCallback(Handler.java:739) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                            at android.os.Looper.loop(Looper.java:139) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5308) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745) 
                                                                        	Suppressed: java.lang.ClassNotFoundException: javax.naming.InitialContext
                                                                            at java.lang.Class.classForName(Native Method)
                                                                            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                            		... 17 more
                                                                         Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available


The line to which the error points is - 
`SpeechToText service = new SpeechToText()`

**Comment by josephlam1984** [comment] 2016-02-01 21:34
It might be helpful to know that this error is thrown in an Android development.

**Comment by germanattanasio** [comment] 2016-02-02 02:22
yeah, I'm going to add `android` to travis along with jdk 7 and 8. I'm going to have a fix for this later this week. You can always use 2.6.0 which doesn't have this problem.

**Comment by germanattanasio** [comment] 2016-03-26 01:14
Seems like this is still happening http://stackoverflow.com/questions/36217233/javax-content-not-accessible

**Comment by germanattanasio** [comment] 2016-04-05 17:51
I've replied to the question and I'm closing this issue because seems like the user was using an old version without the fix for this.

**Closed by germanattanasio** 2016-04-05 17:51 UTC
Labels: bug
